version: '3'
services:
  mongo:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
     - ME_CONFIG_MONGODB_SERVER=mongo
     - ME_CONFIG_MONGODB_PORT=27017
  node:
    depends_on:
      - mongo
    restart: unless-stopped
    build: .
    ports:
      - 3000:3000
    environment:
     - MONGODB_URI=${MONGODB_URI}
     - NODE_ENV=production
     - SECRET=${SECRET}
volumes:
  mongo-data:
    driver: local
