apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: devops-challenge-node:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_USER
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100